---
  version: '2.0'
  services:
    
    mysqldb:
      image: mysql:5.6
      container_name: mysql-db
      ports: 
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: wordpress

    wordpress:
      image: wordpress:4.9
      container_name: wordpress
      restart: always
      ports:
        - 8080:80
      environment:
        WORDPRESS_DB_HOST: "mysqldb:3306"
        WORDPRESS_DB_PASSWORD: wordpress
